version: '3.9'
services:
  frontend:
    container_name: financial_frontend
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: financial_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: postgres
    container_name: financial_db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
    restart: 'always'
    healthcheck:
      # Hel para postgres proveniente do Github go Peter Evans
      # source: https://github.com/peter-evans/docker-compose-healthcheck
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE # Omitir alertas menores