version: '3.9'
services:
  frontend:
    container_name: financial_frontend
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes:
      - ./frontend:/app-frontend
    depends_on:
      - backend

  backend:
    container_name: financial_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      - db_postgres
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - DB_DATABASE=NG_FINANCIAL
  
  db_postgres:
    image: postgres:12
    container_name: db_postgres
    ports:
      - 5432:5432
    platform: linux/x86_64
    restart: 'always'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=NG_FINANCIAL

  
